version: '3'
services:
  db-mysql:
    container_name: db-mysql
    image: mysql
    environment:
      MYSQL_DATABASE: CardGamesDB
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    restart: always